export const WINDOW_COMPONENT_ANIMATION_PLACEHOLDER_ZINDEX_OFFSET = 1;
export const NEW_WINDOW_COMPONENT_ZINDEX_OFFSET = 10;
export const WINDOW_COMPONENT_BORDER_ZINDEX = 200;
export const STARTING_WINDOW_COMPONENT_ZINDEX = 100;
